### ISSUE TITLE
Brain dump

### ISSUE THREAD

**Issue by BitJackson** [MikeRogers0/podcast-app#10]
Few things came to mind while using the app today, thought i'd dump them here and we can discuss.

I really like that it's browser based and i think we could make much more use of 'the web' if we host data in a cloud server or something, rather than letting users dropbox sync.

To use either/or, you would need to be connected to the internet. Even if we dont charge I think we'll be able to offer a much better app/service if when it comes to it, we make a basic website for registering, and just host it as a RESTful API.

means we could looks at socket stuff, we could look at pushing updates, we could even look at things like widgets for 'add this podcast to you EARJIZZ account', or chrome plugins.

We can still put a lot of offline support in, and we can make sure to put in full access to add/remove/edit data, and delete account and stuff.

Not relying on another service. dropbox goes down/under, fucked.

**Comment by MikeRogers0** [comment]
http://codepen.io/hakimel/full/gkeha - These buttons are pretty cool.
