### ISSUE TITLE
onePage branch

### ISSUE THREAD

**Issue by BitJackson** [MikeRogers0/podcast-app#21]
Hey man. 4am coding. 5% battery. commiting for the night.

Started doing some LESS and messing around with layout/shit for reals.

will play around tomorrow getting the elements showing on all pages and such, but im too tired now, just checked into github for safety :)

**Comment by MikeRogers0** [comment]
Cool, I'm going to be working on the cron stuff until like 10am.

**Comment by MikeRogers0** [comment]
I'm going to take a stab at a design idea I had based upon http://i.imgur.com/EsDSOYQ.png
