### ISSUE TITLE
jPlayer

### ISSUE THREAD

**Issue by BitJackson** [MikeRogers0/podcast-app#26]
Went to change some of the styles of the audioplayer, noticed we're using the default browser player, that we cant style/do anything to.

Will look into implementing this soon, and getting it styled, + using the webfont logos i found (have them in pngs if the webfont ends up looking too shit)

http://www.jplayer.org/download/

**Comment by MikeRogers0** [comment]
I'm not a big fan of jPlayer, but if you think it's worth it I can implement it today.

Though have a look at http://kolber.github.io/audiojs/ - it gives us a stye-able element with the same callbacks and a flash fallback. If you want I'll implement today?

**Comment by MikeRogers0** [comment]
Just started on https://github.com/MikeRogers0/podcast-app/tree/audiojs - I need to redo the listners to point to audio.js not the element, but should be done later.
